blogengine/urls.py
from django.conf.urls.defaults import patterns, include, url


urlpatterns = patterns('blogengine.views',
    (r'^$', 'home'),
    (r'^search/$', 'search'),
    (r'^blog/entry/(?P<slug_field>[^\.]+)/$', 'blog_entry_by_slug'),
    (r'^blog/category/(?P<slug_field>[^\.]+)/$', 'category_by_slug'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import haystack
haystack.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djangoblogproject.views.home', name='home'),
    url(r'^', include('djangoblogproject.blogengine.urls')),
    
    url(r'^hitcounter', include('djangoblogproject.hitcounter.urls')),
    
    url(r'^subscribe', include('djangoblogproject.subscribe.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': 'F:/MySource/djangoblogproject/templates/static'},),
)

urlpatterns += patterns('',
    url(r'^pages', include('django.contrib.flatpages.urls')),
)

blogengine/models.py
from django.db import models
from django.contrib.admin.models import User
from autoslug import AutoSlugField
from tinymce import models as tinymce_models

class BlogCategory(models.Model):
    name = models.CharField(max_length = 100)
    slug = AutoSlugField(populate_from = 'name')
    created_on = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User, null = True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/blog/category/" + self.slug

    class Meta:
        verbose_name_plural = "Blog Categories"


class BlogEntry(models.Model):
    title = models.CharField(max_length = 200)
    slug = AutoSlugField(populate_from = 'title', null = True)
    text = tinymce_models.HTMLField()
    category = models.ForeignKey(BlogCategory)
    created_on = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User, null = True)
    
    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/blog/entry/" + self.slug

    class Meta:
        verbose_name_plural = "Blog Entries"

        
        

blogengine/forms.py
from django import forms
from django.forms import ModelForm
from tinymce.widgets import TinyMCE
from models import BlogEntry
from datetime import datetime

class BlogEntryModelForm(ModelForm):
    text = forms.CharField(widget=TinyMCE(attrs={'cols': 160, 'rows': 30, }))


    class Meta:
        model = BlogEntry

blogengine/views.py
from django.http import HttpResponse
from django.template import Context, loader
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.sites.models import Site
from datetime import datetime
from django.views.decorators.gzip import gzip_page
from models import BlogEntry, BlogCategory
from haystack.query import SearchQuerySet



###############################################
###Homepage, Shows the top 1 entry in there
###############################################
@gzip_page
def home(request):
    html_template = 'blogengine/index.htm'
    blog_entries = BlogEntry.objects.all().order_by("-created_on")[:1]
    return render_to_response(html_template,
    {
        'blog_entries':         blog_entries,
        
    }, context_instance=RequestContext(request,))


###############################################
###Shows the search result
###############################################
@gzip_page
def search(request):
    search_term = None
    if request.method == 'GET':
        search_term = request.GET.get('q')
        results = SearchQuerySet().filter(content = search_term)
    html_template = 'blogengine/index.htm'
    return render_to_response(html_template,
    {
        'results': results,
        'search_term': search_term,
        
    }, context_instance=RequestContext(request,))


###############################################
###Shows the blog entry by slug
###############################################
@gzip_page
def blog_entry_by_slug(request, slug_field):
    html_template = 'blogengine/index.htm'
    blog_entry = BlogEntry.objects.filter(slug = slug_field)[0]
    return render_to_response(html_template,
    {
        'blog_entry': blog_entry,
        
    }, context_instance=RequestContext(request,))



###############################################
###Shows the category by slug
###############################################
@gzip_page
def category_by_slug(request, slug_field):
    html_template = 'blogengine/index.htm'
    blog_category = BlogCategory.objects.filter(slug = slug_field)
    blog_entries = BlogEntry.objects.filter(category = blog_category)
    return render_to_response(html_template,
    {
        'blog_entries': blog_entries,
        
    }, context_instance=RequestContext(request,))

templates/blogengine/index.htm
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    {% load mytemplatetags %}	
    {% get_site_name as site_name %}
	<title>Home | {{ site_name }} </title>

	<style type="text/css" media="screen">
		@import url( "{{ MEDIA_URL }}blogengine/style.css" );
	</style>

	<link rel="stylesheet" href="{{ MEDIA_URL }}blogengine/print.css" type="text/css" media="print">

</head>

<body>
<div id="wrap">
	<div id="header">
		<p id="login">
            <a href="/subscribe"><font><font>Subscribe</font></font></a>
        </p>
		<h1>
            <a accesskey="1" href="/#header"><font><font>{{ site_name }}</font></font></a>
        </h1>
		<p>
            <font><font>Yet Another Blog!</font></font>
        </p>
	</div>

	<div id="content">

     {% if results %}
     
        {% for result in results %}
                <div class="post" id="post-{{ result.object.id }}">
                    <h2>
                        <a href="{{ result.object.get_absolute_url }}" rel="bookmark"><font><font>{{ result.object.title|truncatewords:12 }}</font></font>
                        </a>
                    </h2>
                    <div>
                        <font>Written by {{ result.object.created_by.get_full_name }} on {{ result.object.created_on }} </font>| Filed under <a href="{{ result.object.category.get_absolute_url }}">{{ result.object.category.name }}</a>
                    </div>

                    <div class="story">
                    <p>
                        <font>
                            <font>{{ result.object.text|safe }}</font>
                        </font>
                    </p>
                    </div>
                </div>
                
        {% endfor %}
    {% else %}
        {% if search_term %}
        <p>No Search results found</p>
        {% endif %}
    {% endif %}
    

		{% if blog_entries %}
            {% for blog_entry in blog_entries %}
                <div class="post" id="post-{{ blog_entry.id }}">
                    <h2>
                        <a href="{{ blog_entry.get_absolute_url }}" rel="bookmark"><font><font>{{ blog_entry.title|truncatewords:12 }}</font></font>
                        </a>
                    </h2>
                    <div>
                        <font>Written by {{ blog_entry.created_by.get_full_name }} on {{ blog_entry.created_on }} </font>| Filed under <a href="{{ blog_entry.category.get_absolute_url }}">{{ blog_entry.category.name }}</a>
                    </div>
                        
                    <div class="story">
                    <p>
                        <font>
                            <font>{{ blog_entry.text|safe }}</font>
                        </font>
                    </p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
        
        
        {% if blog_entry %}
                <div class="post" id="post-{{ blog_entry.id }}">
                    <h2>
                        <a href="{{ blog_entry.get_absolute_url }}" rel="bookmark"><font><font>{{ blog_entry.title|truncatewords:12 }}</font></font>
                        </a>
                    </h2>
                    <div>
                        <font>Written by {{ blog_entry.created_by.get_full_name }} on {{ blog_entry.created_on }} </font>| Filed under <a href="{{ blog_entry.category.get_absolute_url }}">{{ blog_entry.category.name }}</a>
                    </div>

                        
                    <div class="story">
                    <p>
                        <font>
                            <font>{{ blog_entry.text|safe }}</font>
                        </font>
                    </p>
                    </div>
                
                </div>
        {% endif %}

        
       

	</div>
	
	
	<div id="sidebar">
	<ul>
		<li id="search">
			<form id="searchform" method="get" action="/search">
			<p>
				<input type="text" value="" name="q" id="id_q">
				<font><font><input type="submit" class="submit" accesskey="s" value="Search"></font></font>
			</p>
			</form>
		</li>
        {% load flatpages %}       
        {% get_flatpages as flatpages %}
        {% if flatpages %}
		<li class="pagenav">
            <h2>
                <font><font>Pages</font></font>
            </h2>
            <ul>
                {% for page in flatpages %}
                    <li class="page_item page-item-2"><a href="{{ page.url }}"  title="{{ page.title }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        </li>
		{% endif %}
        
        {% get_latest blogengine.BlogCategory 1000 as blog_categories %}
        {% if blog_categories %}
        <li class="categories">
            <h2>
                <font><font>Categories</font></font>
            </h2>
            <ul>
                
                
                {% for blog_category in blog_categories %}
                    {% if blog_category.blogentry_set.count > 0 %}
                    <li class="cat-item cat-item-1">
                        <a href="{{ blog_category.get_absolute_url }}" title="View all posts filed under Uncategorized">
                            <font>
                                <font>{{ blog_category.name }}</font>
                            </font>
                        </a>
                        <font>
                            <font> ({{ blog_category.blogentry_set.count }})
                            </font>
                        </font>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </li>
        {% endif %}
        
        {% get_latest blogengine.BlogEntry 5 as latest_entries %}
        {% if latest_entries %}
		<li>
            <h2><font><font>Latest posts</font></font></h2>
			<ul>
                
                {% for latest_entry in latest_entries %}
				<li>
                    <a href="{{ latest_entry.get_absolute_url }}" title="{{ latest_entry.title }}">
                        <font><font>{{ latest_entry.title|truncatewords:5 }}</font></font>
                    </a>
                </li>
                {% endfor %}
			</ul>
		</li>
        {% endif %}
        </ul>
	</div>
	
	<div id="footer">
		<p>
            <font>
                <font>© 2011 | </font>
            </font>
                    <a accesskey="1" href="/">
                        <font><font>
                        {{ site_name }}
                        </font></font>
                    </a>
                    <font><font> | </font></font>
                    <small><font><font>
                    
                    
                    <a accesskey="2" href="http://www.djangoproject.com/"><img src="http://media.djangoproject.com/img/badges/djangosite80x15_grey.gif" style="width:80px;height:15px;" border="0" alt="A Django site." title="A Django site." /></a>
                    
                    </font></font></small>
                    <font><font> | </font></font>
                    <a accesskey="3" href="/admin"><font><font>Login</font></font></a>
        </p>
	</div>
	</div>
</body>
</html>

templates/blogengine/search.htm
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    {% load mytemplatetags %}	
    {% get_site_name as site_name %}
	<title>Home | {{ site_name }} </title>

	<style type="text/css" media="screen">
		@import url( "{{ MEDIA_URL }}blogengine/style.css" );
	</style>

	<link rel="stylesheet" href="{{ MEDIA_URL }}blogengine/print.css" type="text/css" media="print">

</head>

<body>
<div id="wrap">
	<div id="header">
		<p id="login">
            <a href="/subscribe"><font><font>Subscribe</font></font></a>
        </p>
		<h1>
            <a accesskey="1" href="/#header"><font><font>{{ site_name }}</font></font></a>
        </h1>
		<p>
            <font><font>Yet Another Blog!</font></font>
        </p>
	</div>

	<div id="content">

    {% if results %}
        {% for result in results %}
            {{ result }}
                <div class="post" id="post-{{ blog_entry.id }}">
                    <h2>
                        <a href="{{ blog_entry.get_absolute_url }}" rel="bookmark"><font><font>{{ result.title|truncatewords:12 }}</font></font>
                        </a>
                    </h2>
                    <div>
                        <font>Written by {{ result.created_by.get_full_name }} on {{ result.created_on }} </font>| Filed under <a href="{{ blog_entry.category.get_absolute_url }}">{{ result.category.name }}</a>
                    </div>
                        
                    <div class="story">
                    <p>
                        <font>
                            <font>{{ result.text|safe }}</font>
                        </font>
                    </p>
                    </div>
                </div>
        
        
        {% endfor %}
    {% else %}
        <p>Praveen</p>
    {% endif %}
    

		
	</div>
	
	
	<div id="sidebar">
	<ul>
		<li id="search">
			<form id="searchform" method="get" action="/search">
			<p>
				<input type="text" value="" name="q" id="id_q">
				<font><font><input type="submit" class="submit" accesskey="s" value="Search"></font></font>
			</p>
			</form>
		</li>
        {% load flatpages %}       
        {% get_flatpages as flatpages %}
        {% if flatpages %}
		<li class="pagenav">
            <h2>
                <font><font>Pages</font></font>
            </h2>
            <ul>
                {% for page in flatpages %}
                    <li class="page_item page-item-2"><a href="{{ page.url }}"  title="{{ page.title }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        </li>
		{% endif %}
        
        {% get_latest blogengine.BlogCategory 1000 as blog_categories %}
        {% if blog_categories %}
        <li class="categories">
            <h2>
                <font><font>Categories</font></font>
            </h2>
            <ul>
                
                
                {% for blog_category in blog_categories %}
                    {% if blog_category.blogentry_set.count > 0 %}
                    <li class="cat-item cat-item-1">
                        <a href="{{ blog_category.get_absolute_url }}" title="View all posts filed under Uncategorized">
                            <font>
                                <font>{{ blog_category.name }}</font>
                            </font>
                        </a>
                        <font>
                            <font> ({{ blog_category.blogentry_set.count }})
                            </font>
                        </font>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </li>
        {% endif %}
        
        {% get_latest blogengine.BlogEntry 5 as latest_entries %}
        {% if latest_entries %}
		<li>
            <h2><font><font>Latest posts</font></font></h2>
			<ul>
                
                {% for latest_entry in latest_entries %}
				<li>
                    <a href="{{ latest_entry.get_absolute_url }}" title="{{ latest_entry.title }}">
                        <font><font>{{ latest_entry.title|truncatewords:5 }}</font></font>
                    </a>
                </li>
                {% endfor %}
			</ul>
		</li>
        {% endif %}
        </ul>
	</div>
	
	<div id="footer">
		<p>
            <font>
                <font>© 2011 | </font>
            </font>
                    <a accesskey="1" href="/">
                        <font><font>
                        {{ site_name }}
                        </font></font>
                    </a>
                    <font><font> | </font></font>
                    <small><font><font>
                    
                    
                    <a accesskey="2" href="http://www.djangoproject.com/"><img src="http://media.djangoproject.com/img/badges/djangosite80x15_grey.gif" style="width:80px;height:15px;" border="0" alt="A Django site." title="A Django site." /></a>
                    
                    </font></font></small>
                    <font><font> | </font></font>
                    <a accesskey="3" href="/admin"><font><font>Login</font></font></a>
        </p>
	</div>
	</div>
</body>
</html>